### ISSUE TITLE
FEAT: display test count (total and why not by file)

### ISSUE THREAD

**Issue by 1000i100** [arlac77/browser-ava#194]
x tests passed
y failed tests
z test skipped

**Comment by 1000i100** [comment]
I see in the code :
- tests failed
- known failure
And i don't understand the difference.
Are test failed only the one that fail for the first time ?
Are known failure thoses who have never pass before ?
Or is it something disconnected from past run ?

**Comment by arlac77** [comment]
*test.todo()* and *test.serial.todo()* count up "tests todo"
*test.failing()* count up "known failure"
and test with failing assertions count up "tests failed"

if You run plain ava

```console
ava tests/fixtures/tests/first-test.mjs
```

You get
```
  5 tests failed
  1 known failure
  2 tests todo
```

nearly the same for browser-ava

```console
 ./src/browser-ava-cli.mjs --chromium tests/fixtures/tests/first-test.mjs
```

```
6 tests failed
1 known failure
2 tests todo
```

6 instead of 5 failures from the none working assertion skip (line 106 of first-test.mjs)
